In [5]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

import warnings
warnings.filterwarnings('ignore')


In [6]:
# Load the data. 
# Used zip file bcse csv file was too big to upload to github.
#df = pd.read_csv('../Resources/2017.csv')
df1 = pd.read_csv('../Resources/clean_data1.csv')
df1.head(3).append(df1.tail(3))

Unnamed: 0     FL_DATE         OP_CARRIER ORIGIN DEST  CRS_DEP_TIME  \
0                3  2017-01-01  American Airlines    DFW  HNL             2   
1                5  2017-01-01  American Airlines    DFW  OGG             2   
2               27  2017-01-01  American Airlines    DFW  SFO             4   
908781     5674588  2017-12-31    United Airlines    DEN  RIC             2   
908782     5674615  2017-12-31    United Airlines    DEN  CID             3   
908783     5674619  2017-12-31    United Airlines    LAS  SFO             2   

        DEP_DELAY  TAXI_OUT  WHEELS_OFF  WHEELS_ON  TAXI_IN  CRS_ARR_TIME  \
0            77.0      19.0           3          3      5.0             3   
1           399.0      12.0           3          4      6.0             3   
2             6.0      18.0           4          4      8.0             4   
908781       -8.0      11.0           2          3      7.0             3   
908782       -2.0      12.0           3          3      8.0             3   
908783       -8.0      11.0           2          3     15.0             3   

        ARR_DELAY  CRS_ELAPSED_TIME  ACTUAL_ELAPSED_TIME  AIR_TIME  DISTANCE  \
0            97.0             517.0                537.0     513.0    3784.0   
1           394.0             503.0                498.0     480.0    3711.0   
2            10.0             237.0                241.0     215.0    1464.0   
908781      -43.0             206.0                171.0     153.0    1482.0   
908782      -13.0             115.0                104.0      84.0     692.0   
908783      -15.0              99.0                 92.0      66.0     414.0   

        FLIGHT_STATUS  DAY  MONTH  
0                   1    1      1  
1                   1    1      1  
2                   1    1      1  
908781              0   31     12  
908782              0   31     12  
908783              0   31     12

In [7]:
df2 = pd.read_csv('../Resources/clean_data2.csv')
df2.head(3).append(df2.tail(3))

Unnamed: 0     FL_DATE         OP_CARRIER ORIGIN DEST  CRS_DEP_TIME  \
0                1  2017-01-01  American Airlines    LAX  JFK             2   
1                2  2017-01-01  American Airlines    LAX  JFK             2   
2                8  2017-01-01  American Airlines    LAX  JFK             4   
934142     5674583  2017-12-31    United Airlines    ORD  SAN             3   
934143     5674600  2017-12-31    United Airlines    SFO  HNL             4   
934144     5674602  2017-12-31    United Airlines    SFO  IAH             1   

        DEP_DELAY  TAXI_OUT  WHEELS_OFF  WHEELS_ON  TAXI_IN  CRS_ARR_TIME  \
0            34.0      34.0           2          3     12.0             3   
1            51.0      20.0           3          4     15.0             4   
2             0.0      15.0           4          1     10.0             1   
934142      111.0      16.0           3          3      3.0             3   
934143       -7.0      14.0           4          4      3.0             4   
934144       -4.0      16.0           1          2     10.0             2   

        ARR_DELAY  CRS_ELAPSED_TIME  ACTUAL_ELAPSED_TIME  AIR_TIME  DISTANCE  \
0            42.0             327.0                335.0     289.0    2475.0   
1            42.0             328.0                319.0     284.0    2475.0   
2           -30.0             327.0                297.0     272.0    2475.0   
934142      103.0             266.0                258.0     239.0    1723.0   
934143      -43.0             358.0                322.0     305.0    2398.0   
934144      -13.0             232.0                223.0     197.0    1635.0   

        FLIGHT_STATUS  DAY  MONTH  
0                   1    1      1  
1                   1    1      1  
2                   0    1      1  
934142              1   31     12  
934143              0   31     12  
934144              0   31     12

In [8]:
nine_cities = df1.append(df2)

In [9]:
nine_cities.head(3).append(df2.tail(3))

Unnamed: 0     FL_DATE         OP_CARRIER ORIGIN DEST  CRS_DEP_TIME  \
0                3  2017-01-01  American Airlines    DFW  HNL             2   
1                5  2017-01-01  American Airlines    DFW  OGG             2   
2               27  2017-01-01  American Airlines    DFW  SFO             4   
934142     5674583  2017-12-31    United Airlines    ORD  SAN             3   
934143     5674600  2017-12-31    United Airlines    SFO  HNL             4   
934144     5674602  2017-12-31    United Airlines    SFO  IAH             1   

        DEP_DELAY  TAXI_OUT  WHEELS_OFF  WHEELS_ON  TAXI_IN  CRS_ARR_TIME  \
0            77.0      19.0           3          3      5.0             3   
1           399.0      12.0           3          4      6.0             3   
2             6.0      18.0           4          4      8.0             4   
934142      111.0      16.0           3          3      3.0             3   
934143       -7.0      14.0           4          4      3.0             4   
934144       -4.0      16.0           1          2     10.0             2   

        ARR_DELAY  CRS_ELAPSED_TIME  ACTUAL_ELAPSED_TIME  AIR_TIME  DISTANCE  \
0            97.0             517.0                537.0     513.0    3784.0   
1           394.0             503.0                498.0     480.0    3711.0   
2            10.0             237.0                241.0     215.0    1464.0   
934142      103.0             266.0                258.0     239.0    1723.0   
934143      -43.0             358.0                322.0     305.0    2398.0   
934144      -13.0             232.0                223.0     197.0    1635.0   

        FLIGHT_STATUS  DAY  MONTH  
0                   1    1      1  
1                   1    1      1  
2                   1    1      1  
934142              1   31     12  
934143              0   31     12  
934144              0   31     12

In [10]:
nine_cities.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1842929 entries, 0 to 934144
Data columns (total 20 columns):
 #   Column               Dtype  
---  ------               -----  
 0   Unnamed: 0           int64  
 1   FL_DATE              object 
 2   OP_CARRIER           object 
 3   ORIGIN               object 
 4   DEST                 object 
 5   CRS_DEP_TIME         int64  
 6   DEP_DELAY            float64
 7   TAXI_OUT             float64
 8   WHEELS_OFF           int64  
 9   WHEELS_ON            int64  
 10  TAXI_IN              float64
 11  CRS_ARR_TIME         int64  
 12  ARR_DELAY            float64
 13  CRS_ELAPSED_TIME     float64
 14  ACTUAL_ELAPSED_TIME  float64
 15  AIR_TIME             float64
 16  DISTANCE             float64
 17  FLIGHT_STATUS        int64  
 18  DAY                  int64  
 19  MONTH                int64  
dtypes: float64(8), int64(8), object(4)
memory usage: 295.3+ MB


In [11]:
nine_cities = nine_cities.drop(["Unnamed: 0","FL_DATE","TAXI_OUT","WHEELS_OFF","WHEELS_ON","TAXI_IN","ARR_DELAY"], axis=1)

In [14]:
nine_cities.shape

(1842929, 13)

In [15]:
nine_cities.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1842929 entries, 0 to 934144
Data columns (total 13 columns):
 #   Column               Dtype  
---  ------               -----  
 0   OP_CARRIER           object 
 1   ORIGIN               object 
 2   DEST                 object 
 3   CRS_DEP_TIME         int64  
 4   DEP_DELAY            float64
 5   CRS_ARR_TIME         int64  
 6   CRS_ELAPSED_TIME     float64
 7   ACTUAL_ELAPSED_TIME  float64
 8   AIR_TIME             float64
 9   DISTANCE             float64
 10  FLIGHT_STATUS        int64  
 11  DAY                  int64  
 12  MONTH                int64  
dtypes: float64(5), int64(5), object(3)
memory usage: 196.8+ MB


In [16]:
nine_cities.isna().sum()

OP_CARRIER             0
ORIGIN                 0
DEST                   0
CRS_DEP_TIME           0
DEP_DELAY              0
CRS_ARR_TIME           0
CRS_ELAPSED_TIME       0
ACTUAL_ELAPSED_TIME    0
AIR_TIME               0
DISTANCE               0
FLIGHT_STATUS          0
DAY                    0
MONTH                  0
dtype: int64

In [17]:
nine_cities.FLIGHT_STATUS.value_counts(normalize=True)

0    0.608657
1    0.391343
Name: FLIGHT_STATUS, dtype: float64

In [12]:
nine_cities.head()

OP_CARRIER ORIGIN DEST  CRS_DEP_TIME  DEP_DELAY  CRS_ARR_TIME  \
0  American Airlines    DFW  HNL             2       77.0             3   
1  American Airlines    DFW  OGG             2      399.0             3   
2  American Airlines    DFW  SFO             4        6.0             4   
3  American Airlines    DFW  DTW             2       -1.0             3   
4  American Airlines    DFW  STL             3       -1.0             4   

   CRS_ELAPSED_TIME  ACTUAL_ELAPSED_TIME  AIR_TIME  DISTANCE  FLIGHT_STATUS  \
0             517.0                537.0     513.0    3784.0              1   
1             503.0                498.0     480.0    3711.0              1   
2             237.0                241.0     215.0    1464.0              1   
3             154.0                134.0     117.0     986.0              0   
4              97.0                 88.0      71.0     550.0              0   

   DAY  MONTH  
0    1      1  
1    1      1  
2    1      1  
3    1      1  
4    1      1

### One Hot Encoding 

In [13]:
ml_df = pd.get_dummies(nine_cities)

In [14]:
ml_df.head()

CRS_DEP_TIME  DEP_DELAY  CRS_ARR_TIME  CRS_ELAPSED_TIME  \
0             2       77.0             3             517.0   
1             2      399.0             3             503.0   
2             4        6.0             4             237.0   
3             2       -1.0             3             154.0   
4             3       -1.0             4              97.0   

   ACTUAL_ELAPSED_TIME  AIR_TIME  DISTANCE  FLIGHT_STATUS  DAY  MONTH  ...  \
0                537.0     513.0    3784.0              1    1      1  ...   
1                498.0     480.0    3711.0              1    1      1  ...   
2                241.0     215.0    1464.0              1    1      1  ...   
3                134.0     117.0     986.0              0    1      1  ...   
4                 88.0      71.0     550.0              0    1      1  ...   

   DEST_TUS  DEST_TVC  DEST_TXK  DEST_TYR  DEST_TYS  DEST_UIN  DEST_VLD  \
0         0         0         0         0         0         0         0   
1         0         0         0         0         0         0         0   
2         0         0         0         0         0         0         0   
3         0         0         0         0         0         0         0   
4         0         0         0         0         0         0         0   

   DEST_VPS  DEST_XNA  DEST_YUM  
0         0         0         0  
1         0         0         0  
2         0         0         0  
3         0         0         0  
4         0         0         0  

[5 rows x 298 columns]

In [15]:
ml_df.shape

(1842929, 298)

## Machine Learning

In [16]:
%matplotlib inline
from matplotlib import pyplot as plt
from sklearn.datasets import make_classification
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import AdaBoostClassifier

In [17]:
ml_df.head()

CRS_DEP_TIME  DEP_DELAY  CRS_ARR_TIME  CRS_ELAPSED_TIME  \
0             2       77.0             3             517.0   
1             2      399.0             3             503.0   
2             4        6.0             4             237.0   
3             2       -1.0             3             154.0   
4             3       -1.0             4              97.0   

   ACTUAL_ELAPSED_TIME  AIR_TIME  DISTANCE  FLIGHT_STATUS  DAY  MONTH  ...  \
0                537.0     513.0    3784.0              1    1      1  ...   
1                498.0     480.0    3711.0              1    1      1  ...   
2                241.0     215.0    1464.0              1    1      1  ...   
3                134.0     117.0     986.0              0    1      1  ...   
4                 88.0      71.0     550.0              0    1      1  ...   

   DEST_TUS  DEST_TVC  DEST_TXK  DEST_TYR  DEST_TYS  DEST_UIN  DEST_VLD  \
0         0         0         0         0         0         0         0   
1         0         0         0         0         0         0         0   
2         0         0         0         0         0         0         0   
3         0         0         0         0         0         0         0   
4         0         0         0         0         0         0         0   

   DEST_VPS  DEST_XNA  DEST_YUM  
0         0         0         0  
1         0         0         0  
2         0         0         0  
3         0         0         0  
4         0         0         0  

[5 rows x 298 columns]

In [24]:
#Create features (X) and lables (y)
y = ml_df["FLIGHT_STATUS"]
X = ml_df.drop(["FLIGHT_STATUS"], axis=1)

#### Train Test split Unscaled

In [64]:
# Train Test split Unscaled
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.20, random_state=42)

#### Train Test split Scaled

In [70]:
# Train Test split scaled
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.20, random_state=42)
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Random Forest Model

#### Unscaled

In [56]:
# from sklearn.metrics import classification_report
#target_names = ["negative", "positive"]
clf = RandomForestClassifier(n_estimators=100, max_depth=5).fit(X_train, y_train)
# y_pred = clf.predict(X_train)
# print(classification_report(y_test, y_pred, target_names=target_names))
print(f'Training Score: {clf.score(X_train, y_train)}')
print(f'Testing Score: {clf.score(X_test, y_test)}')

Training Score: 0.7482404026742759
Testing Score: 0.748441340691182


#### Scaled

In [62]:
# from sklearn.metrics import classification_report
#target_names = ["negative", "positive"]
clf = RandomForestClassifier(n_estimators=100, max_depth=5).fit(X_train_scaled, y_train)
# y_pred = clf.predict(X_train)
# print(classification_report(y_test, y_pred, target_names=target_names))
print(f'Training Score: {clf.score(X_train_scaled, y_train)}')
print(f'Testing Score: {clf.score(X_test_scaled, y_test)}')

Training Score: 0.7952749122829627
Testing Score: 0.7948267161530823


### Logistic Regression Model

In [60]:
lr = LogisticRegression().fit(X_train, y_train)
print(f'Training Score: {lr.score(X_train, y_train)}')
print(f'Testing Score: {lr.score(X_test, y_test)}')

Training Score: 0.9999857563674125
Testing Score: 0.999978295431731


### AdaBoostClassifier

#### Unscaled

In [65]:
from sklearn.ensemble import AdaBoostClassifier
#target_names = ["negative", "positive"]
abc = AdaBoostClassifier(random_state=1).fit(X_train, y_train)
# print(classification_report(y_test, y_pred, target_names=target_names))
print(f'Training Score: {abc.score(X_train, y_train)}')
print(f'Testing Score: {abc.score(X_test, y_test)}')

Training Score: 0.8390795086353718
Testing Score: 0.8391637229845952


#### Scaled

In [63]:
# SCALED
from sklearn.ensemble import AdaBoostClassifier
#target_names = ["negative", "positive"]
abc = AdaBoostClassifier(random_state=1).fit(X_train_scaled, y_train)
# print(classification_report(y_test, y_pred, target_names=target_names))
print(f'Training Score: {abc.score(X_train_scaled, y_train)}')
print(f'Testing Score: {abc.score(X_test_scaled, y_test)}')

Training Score: 0.8390795086353718
Testing Score: 0.8391637229845952


### Neural Network Model

### NN Model 1

In [34]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# First hidden layer

nn.add(tf.keras.layers.Dense(units=30, activation="relu", input_dim=297))

# Second hidden layer

nn.add(tf.keras.layers.Dense(units=20, activation="relu"))

# Output layer

nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 30)                8940      
                                                                 
 dense_6 (Dense)             (None, 20)                620       
                                                                 
 dense_7 (Dense)             (None, 1)                 21        
                                                                 
Total params: 9,581
Trainable params: 9,581
Non-trainable params: 0
_________________________________________________________________


In [35]:
# Compile the model

nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [36]:
# Train the model

fit_model = nn.fit(X_train_scaled, y_train, epochs=2)

Epoch 1/2
46074/46074 [==============================] - 103s 2ms/step - loss: 0.1420 - accuracy: 0.9374
Epoch 2/2
46074/46074 [==============================] - 97s 2ms/step - loss: 0.0824 - accuracy: 0.9640


### NN Model 2

In [31]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# First hidden layer

nn.add(tf.keras.layers.Dense(units=30, activation="relu", input_dim=297))

# Output layer

nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 30)                8940      
                                                                 
 dense_4 (Dense)             (None, 1)                 31        
                                                                 
Total params: 8,971
Trainable params: 8,971
Non-trainable params: 0
_________________________________________________________________


In [32]:
# Compile the model

nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [33]:
# Train the model

fit_model = nn.fit(X_train_scaled, y_train, epochs=2)

Epoch 1/2
46074/46074 [==============================] - 126s 3ms/step - loss: 0.1530 - accuracy: 0.9383
Epoch 2/2
46074/46074 [==============================] - 128s 3ms/step - loss: 0.0847 - accuracy: 0.9685


In [18]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# First hidden layer

nn.add(tf.keras.layers.Dense(units=30, activation="relu", input_dim=297))

# Output layer

nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                8940      
                                                                 
 dense_1 (Dense)             (None, 1)                 31        
                                                                 
Total params: 8,971
Trainable params: 8,971
Non-trainable params: 0
_________________________________________________________________


### NN Model 3

In [19]:
# Compile the model

nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [121]:
# Train the model

fit_model = nn.fit(X_train_scaled, y_train, epochs=2)

Epoch 1/2
46074/46074 [==============================] - 206s 4ms/step - loss: 0.1305 - accuracy: 0.9500
Epoch 2/2
46074/46074 [==============================] - 211s 5ms/step - loss: 0.0835 - accuracy: 0.9696


In [123]:
nn.predict(X_test_2017)

2/2 [==============================] - 0s 3ms/step


array([[0.       ],
       [0.9997496],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [1.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [1.       ],
       [0.6406074],
       [0.       ],
       [1.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ]], dtype=float32)

## Saving the Model

In [53]:
from keras.models import load_model

In [54]:
nn.save("model_nn.h5")

In [55]:
#nn_model = load_model("model_nn.h5")

### Importing 2017 test data for prediction

In [101]:
df_test_2017 = pd.read_csv('../Resources/Test_data_2017.csv')
df_test_2017.head()

CRS_DEP_TIME  DEP_DELAY  CRS_ARR_TIME  CRS_ELAPSED_TIME  \
0             4       -6.0             4             111.0   
1             3       14.0             3             107.0   
2             4       24.0             4             103.0   
3             3       92.0             3             166.0   
4             4        0.0             4             148.0   

   ACTUAL_ELAPSED_TIME  AIR_TIME  DISTANCE  FLIGHT_STATUS  DAY  MONTH  ...  \
0                122.0      99.0     622.0              1   23     10  ...   
1                126.0      81.0     466.0              1   19      5  ...   
2                 90.0      69.0     453.0              1   30      1  ...   
3                165.0     143.0     967.0              1   20      2  ...   
4                148.0     119.0     868.0              1   18      7  ...   

   DEST_TUS  DEST_TVC  DEST_TXK  DEST_TYR  DEST_TYS  DEST_UIN  DEST_VLD  \
0         0         0         0         0         0         0         0   
1         0         0         0         0         0         0         0   
2         0         0         0         0         0         0         0   
3         0         0         0         0         0         0         0   
4         0         0         0         0         0         0         0   

   DEST_VPS  DEST_XNA  DEST_YUM  
0         0         0         0  
1         0         0         0  
2         0         0         0  
3         0         0         0  
4         0         0         0  

[5 rows x 298 columns]

In [103]:
df_test_2017.shape

(40, 298)

In [106]:
#Create features (X) and lables (y)
y_test_2017 = df_test_2017["FLIGHT_STATUS"]
X_test_2017 = df_test_2017.drop(["FLIGHT_STATUS"], axis=1)

## Testing the Model

### Testing the Random Forest Model

In [71]:
clf = RandomForestClassifier(n_estimators=100, max_depth=5).fit(X_train_scaled, y_train)

In [74]:
clf.predict(X_test)

array([0, 1, 1, ..., 0, 1, 0], dtype=int64)

In [109]:
clf.predict(X_test_2017)

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

### Testing the AdaBoostClassifier Model

In [77]:
abc = AdaBoostClassifier(random_state=1).fit(X_train, y_train)

In [111]:
abc.predict(X_test_2017)

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

### Testing the Neural Network Model

In [99]:
nn_model.predict(X_test_scaled)

11519/11519 [==============================] - 40s 4ms/step


array([[3.1087362e-07],
       [9.9998397e-01],
       [9.9986428e-01],
       ...,
       [3.2272392e-15],
       [9.9990994e-01],
       [5.2501580e-08]], dtype=float32)

In [94]:
nn_model.predict(X_test)

11519/11519 [==============================] - 43s 4ms/step


array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [115]:
nn.predict(X_test_2017)

2/2 [==============================] - 0s 26ms/step


array([[0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.2354017e-10],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00]], dtype=float32)

In [114]:
df_test_2017["FLIGHT_STATUS"]

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
Name: FLIGHT_STATUS, dtype: int64